### PR TITLE
Support laravel 5

### PR DESCRIPTION
**Pull request by yocmen**

### CODE REVIEW

**Comment by yocmen** [comment]
im new with github, can u tell me whats was wrong? thx in advance.

**Comment by fitztrev** [comment]
@yocmen Here are the build errors https://travis-ci.org/fitztrev/laravel-html-minify/jobs/52204707

I haven't had a chance to review yet but I'll try and take a look this weekend. Thanks again.

**Comment by yocmen** [comment]
thanks to u for this work!.

**Comment by tomexx** [comment]
Sorry guys, any update on this? Thanks!

**Comment by yocmen** [comment]
I updated the package https://packagist.org/packages/yocmen/html-minify

**Pull request closed without merging**
